version: 2
updates:
  - package-ecosystem: gomod
    directory: /gcloud-project
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
